name: ascii workflow

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Run Repo
              run: |
                chmod +x ./testscript.sh
                ./testscript2.sh

    asciijob2:
        runs-on: ubuntu-latest
        needs: [ascii_jobs]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Run Repo
              run: |
                chmod +x ./testscript2.sh
                ./testscript.sh
