name: ascii workflow

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Install Cowsay
              run: |
                sudo apt-get install cowsay -y
            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Hello run away" >> ascci.txt

            - name: Test Files Exists
              run: grep -i "ascci" 