name: ascii workflow

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        outputs:
            script_status: ${{steps.run_script.outputs.status}}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Run Repo
              id: run_script
              run: |
                chmod +x ./testscript2.sh
                ./testscript2.sh
                echo "{status}={success}" >> $GITHUB_OUTPUT

    asciijob2:
        runs-on: ubuntu-latest
        needs: [ascii_jobs]
        steps:
            - name: Run Repo
              run: |
                echo "Previous job status ${{needs.ascii_jobs.outputs.status}}"
