name: matrix stratergy

on:
    push:
    workflow_dispatch:


jobs:
    run_image_job:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest,windows-latest]
                images: [nginx,alpine]
                exclude:
                    - images: alpine
                      os: windows-latest
        runs-on: ${{matrix.os}}
        steps:
            - name: Run Docker
              run: docker run ${{matrix.images}}